# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.0
_src_path: git+https://stefanschuhart@bitbucket.org/geowerkstatt-hamburg/python_project_template.git
author_email: stefan.schuhart@gv.hamburg.de
author_fullname: Stefan Schuhart
author_git_username: StefanSchuhart
create_global_environment: false
create_project_environment: false
docker_image_distribution: bookworm
initial_commit: true
is_datascience_project: false
package_manager: poetry
project_description: A library to create a FastAPI-based  OGC API Processes wrapper
    around existing projects.
project_name: fastProcesses
python_package_distribution_name: fastprocesses
python_package_import_name: fastprocesses
python_version: '3.12'
repository_namespace: geowerkstatt-hamburg
repository_provider: github.com
