networks:
  dev:
    name: ${DOCKER_DEV_NETWORK}
    external: true

services:
  app:
    image: ${CONTAINER_REGISTRY}/analytics/${IMAGE_NAME}:${IMAGE_TAG}
    restart: "unless-stopped"
    # environment:
    #   MY_ENV_VAR1: ${MY_ENV_VAR1}
    # ports:
    #   - ${WEBAPP_PORT_CONTAINER}:${WEBAPP_PORT}
    command: ['src/app.py']

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    expose: 
      - ${REDIS_PORT}
    restart: "unless-stopped"
    # command: dragonfly --requirepass ${REDIS_PASSWORD} # --appendonly yes
    networks: 
      - dev
